### ISSUE TITLE
Séparer l'application Android et le WS

### ISSUE THREAD

**Issue by olivernight** [burellierc/pokecard#1]
Pourquoi est ce que tu versionnes l'application web dans le même projet que ton application Android ? 
Il faut créer un repo dédié à l'application web et 1 repo dédié à l'application mobile

**Comment by burellierc** [comment]
On a créé 2 répertoires, un androidApp et un webApp dans le projet, mais d’accord je vais recréer un repo dédié à l’application web.

**Comment by olivernight** [comment]
Oui car tu vas te retrouver à devoir faire des pull pour mettre à jour ta copie locale parce que y aura eu des maj sur l’application Android alors que toi tu veux juste bosser sur l api par exemple

**Comment by burellierc** [comment]
Ok merci bien.

**Comment by olivernight** [comment]
Je te conseille d assigner la tâche à toi ou à ton binôme et de la noter dans votre planning, ça vous fait une tache en plus affectée :)
